// Code generated by MockGen. DO NOT EDIT.
// Source: cgcp/memorystore.go

// Package cgcp is a generated GoMock package.
package cgcp

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemoryStoreClient is a mock of MemoryStoreClient interface.
type MockMemoryStoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryStoreClientMockRecorder
}

// MockMemoryStoreClientMockRecorder is the mock recorder for MockMemoryStoreClient.
type MockMemoryStoreClientMockRecorder struct {
	mock *MockMemoryStoreClient
}

// NewMockMemoryStoreClient creates a new mock instance.
func NewMockMemoryStoreClient(ctrl *gomock.Controller) *MockMemoryStoreClient {
	mock := &MockMemoryStoreClient{ctrl: ctrl}
	mock.recorder = &MockMemoryStoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryStoreClient) EXPECT() *MockMemoryStoreClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMemoryStoreClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMemoryStoreClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMemoryStoreClient)(nil).Close))
}

// Delete mocks base method.
func (m *MockMemoryStoreClient) Delete(ctx context.Context, keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMemoryStoreClientMockRecorder) Delete(ctx interface{}, keys ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, keys...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMemoryStoreClient)(nil).Delete), varargs...)
}

// GetInt mocks base method.
func (m *MockMemoryStoreClient) GetInt(ctx context.Context, key string, value *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInt", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetInt indicates an expected call of GetInt.
func (mr *MockMemoryStoreClientMockRecorder) GetInt(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInt", reflect.TypeOf((*MockMemoryStoreClient)(nil).GetInt), ctx, key, value)
}

// GetJSON mocks base method.
func (m *MockMemoryStoreClient) GetJSON(ctx context.Context, key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockMemoryStoreClientMockRecorder) GetJSON(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockMemoryStoreClient)(nil).GetJSON), ctx, key, value)
}

// GetString mocks base method.
func (m *MockMemoryStoreClient) GetString(ctx context.Context, key string, value *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetString indicates an expected call of GetString.
func (mr *MockMemoryStoreClientMockRecorder) GetString(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockMemoryStoreClient)(nil).GetString), ctx, key, value)
}

// SetInt mocks base method.
func (m *MockMemoryStoreClient) SetInt(ctx context.Context, key string, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInt", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInt indicates an expected call of SetInt.
func (mr *MockMemoryStoreClientMockRecorder) SetInt(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInt", reflect.TypeOf((*MockMemoryStoreClient)(nil).SetInt), ctx, key, value)
}

// SetJSON mocks base method.
func (m *MockMemoryStoreClient) SetJSON(ctx context.Context, key string, value interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSON", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSON indicates an expected call of SetJSON.
func (mr *MockMemoryStoreClientMockRecorder) SetJSON(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSON", reflect.TypeOf((*MockMemoryStoreClient)(nil).SetJSON), ctx, key, value)
}

// SetString mocks base method.
func (m *MockMemoryStoreClient) SetString(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetString", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetString indicates an expected call of SetString.
func (mr *MockMemoryStoreClientMockRecorder) SetString(ctx, key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetString", reflect.TypeOf((*MockMemoryStoreClient)(nil).SetString), ctx, key, value)
}
