#!/bin/bash

set -e

$(go env GOPATH)/bin/mockgen \
    --self_package=github.com/suzuito/common-go/clogger \
    --package=clogger \
    --source=clogger/a.go \
    --destination=clogger/a_mock.go
$(go env GOPATH)/bin/mockgen \
    --self_package=github.com/suzuito/common-go/application \
    --package=application \
    --source=application/a.go \
    --destination=application/a_mock.go
$(go env GOPATH)/bin/mockgen \
    --self_package=github.com/suzuito/common-go/cgcp \
    --package=cgcp \
    --source=cgcp/wrapper.go \
    --destination=cgcp/wrapper_mock.go

$(go env GOPATH)/bin/mockgen \
    --self_package=github.com/suzuito/common-go/cgcp \
    --package=cgcp \
    --source=cgcp/memorystore.go \
    --destination=cgcp/memorystore_mock.go