#!/bin/sh

set -e

DIR_ARTIFACTS=/tmp/artifacts
FILE_COV=${DIR_ARTIFACTS}/main.cov
FILE_HTML=${DIR_ARTIFACTS}/index.html

rm -rf ${DIR_ARTIFACTS}
mkdir -p ${DIR_ARTIFACTS}

go test -timeout 30s -coverprofile=${FILE_COV} ./...
go tool cover -html=${FILE_COV} -o ${FILE_HTML}

set +e
