#!/bin/sh

set -e

rm -rf /tmp/artifacts
mkdir -p /tmp/artifacts
go test -timeout 30s ./...

set +e

for n in 'cgin'; do
    mkdir -p /tmp/artifacts/go-code-cover/${n}
    go test -coverprofile=/tmp/artifacts/go-code-cover/${n}.cov -timeout 30s github.com/suzuito/common-go/${n} && go tool cover -html=/tmp/artifacts/go-code-cover/${n}.cov -o /tmp/artifacts/go-code-cover/${n}.html
done